{% set version="6.0.0" %}

package:
  name: clang
  version: {{ version }}

source:
  - url: http://releases.llvm.org/{{ version }}/llvm-{{ version }}.src.tar.xz
    sha256: 1ff53c915b4e761ef400b803f07261ade637b0c269d99569f18040f3dcee4408
    patches:
      - patches/0001-turn-off-libxml2-as-it-is-used-only-for-testing-or-w.patch
      - patches/0002-disable-Ocaml-and-Go-bindings.patch
      - patches/0003-replace-include-FindPythonInterp-by-find_package-Pyt.patch
      - patches/0004-disable-git.patch
      - patches/0005-force-tinfo.patch
      - patches/0006-force-libedit.patch
      - patches/0007-CMake-llvm_setup_rpath-honor-CMAKE_SKIP_INSTALL_RPAT.patch
  - url: http://releases.llvm.org/{{ version }}/cfe-{{ version }}.src.tar.xz
    sha256: e07d6dd8d9ef196cfc8e8bb131cbd6a2ed0b1caf1715f9d05b0f0eeaddb6df32
    folder: tools/clang
    patches:
      - patches/tools/clang/0001-turn-off-libxml2-as-it-is-used-only-for-testing-or-w.patch
  - url: http://releases.llvm.org/{{ version }}/clang-tools-extra-{{ version }}.src.tar.xz
    sha256: 053b424a4cd34c9335d8918734dd802a8da612d13a26bbb88fcdf524b2d989d2
    folder: tools/clang/tools/extra

build:
  number: 6
  run_exports:
    - {{ pin_subpackage('clang') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.4.3
    - ninja
    # used for build, python 2 used because conda post-install compiles the python files,
    # and not all of them are python 3 compatible
    - python 2
    - pkg-config                # [unix]
  host:
    - libedit                   # [unix]
    - ncurses                   # [unix]

about:
  home: https://clang.llvm.org/
  doc_url: https://clang.llvm.org/docs/index.html
  license: University of Illinois/NCSA Open Source License
  license_family: BSD
  license_file: LICENSE.TXT
  summary: a C language family frontend for LLVM

extra:
  recipe-maintainers:
    - Sarcasm
