{% set version = "1.0.2" %}

package:
  name: cppgraphqlgen
  version: {{ version }}

source:
  url: https://github.com/Microsoft/cppgraphqlgen/archive/v{{ version }}.tar.gz
  sha256: 6051ea08e37ec50ad1864303539b5ca8b5a744204e1bb5316241256ad287705e
  # url: https://github.com/Microsoft/cppgraphqlgen/archive/faddbd0be73a73b9fcd23ef3b0f20fce33bde8ff.zip
  # sha256: 5f8e135be964a88fb90124ec88df36a1a37048ebb78c144b1951334463616d25
  # patches:
  #   - 0001-move-public-headers-to-graphqlservice-directory.patch
  #   - 0002-CMake-use-Threads-Threads-instead-of-CMAKE_THREAD_LI.patch
  #   - 0003-CMake-replace-CXX_STANDARD-by-target_compile_feature.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - pegtl
    # tests dependencies
    - rapidjson
    - gtest
  run:
    - pegtl

# test:
#   commands:
#     - test -d ${PREFIX}/include/graphqlparser               # [unix]
#     - test -f ${PREFIX}/lib/libgraphqlparser.so             # [linux]
#     - conda inspect linkages -p $PREFIX libgraphqlparser    # [unix]

about:
  home: https://github.com/Microsoft/cppgraphqlgen
  license: MIT
  license_file: LICENSE
  summary: C++ GraphQL schema service generator
  description: |
    C++ GraphQL schema service generator

extra:
  recipe-maintainers:
    - Sarcasm
