{% set version = "0.6" %}

package:
  name: cppgraphqlgen
  version: {{ version }}

source:
  url: https://github.com/Microsoft/cppgraphqlgen/archive/v{{ version }}.tar.gz
  sha256: 21c7b43e28d0f95fb4595aa9d195b4898689060ab89ebb3abfd6b0c52139697f
patches:
  - 0001-CMake-remove-explicit-addition-of-std-c-11-compile-o.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - pegtl
    - rapidjson
  run:
    - pegtl
    - rapidjson

# test:
#   commands:
#     - test -d ${PREFIX}/include/graphqlparser               # [unix]
#     - test -f ${PREFIX}/lib/libgraphqlparser.so             # [linux]
#     - conda inspect linkages -p $PREFIX libgraphqlparser    # [unix]

about:
  home: https://github.com/Microsoft/cppgraphqlgen
  license: MIT
  license_file: LICENSE
  summary: C++ GraphQL schema service generator
  description: |
    C++ GraphQL schema service generator

extra:
  recipe-maintainers:
    - Sarcasm
