{% set version = "1.8.0" %}

package:
  name: gmock
  version: {{ version }}

requirements:
  build:
    - googletest-gmock-build {{ version }}

build:
  number: 0
  always_include_files:
    - include/gmock
    - lib/libgmock*

test:
  commands:
    - test -f $PREFIX/include/gmock/gmock.h           # [unix]

about:
  home: https://github.com/google/googletest
  license: BSD 3-Clause
  license_family: BSD
  license_url: https://raw.githubusercontent.com/google/googletest/release-1.8.0/googlemock/LICENSE
  summary: Google C++ mocking framework

extra:
  recipe-maintainers:
    - Sarcasm
