{% set version = "2.7.1" %}

package:
  name: pegtl
  version: {{ version }}

source:
  url: https://github.com/taocpp/PEGTL/archive/{{ version }}.tar.gz
  sha256: af68ee953d4efc48e090722f8cb9ad4ef1140f6a5443581563e003e060376718

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
