{% set version = "1.8.0" %}
{% set sha256 = "58a6f4277ca2bc8565222b3bbd58a177609e9c488e8a72649359ba51450db7d8" %}

package:
  name: googletest-meta
  version: {{ version }}

source:
  fn: googletest-release-1.8.0.tar.gz
  url: https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  sha256: {{ sha256 }}

build:
  number: 6

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

outputs:
  - name: gtest
    files:
      - include/gtest
      - lib/libgtest*
    about:
      home: https://github.com/google/googletest
      license: BSD 3-Clause
      license_family: BSD
      license_url: https://raw.githubusercontent.com/google/googletest/release-1.8.0/googletest/LICENSE
      summary: Google C++ test framework
    test:
      script: run_test_gtest.sh
  - name: gmock
    requirements:
      run:
        - {{ pin_subpackage('gtest', exact=True) }}
    files:
      - include/gmock
      - lib/libgmock*
    about:
      home: https://github.com/google/googletest
      license: BSD 3-Clause
      license_family: BSD
      license_url: https://raw.githubusercontent.com/google/googletest/release-1.8.0/googlemock/LICENSE
      summary: Google C++ mocking framework
    test:
      script: run_test_gmock.sh

extra:
  recipe-maintainers:
    - Sarcasm
