{% set version = "4.1.0" %}
{% set sha256 = "9d49bf02ceb9d0eec51144b203b63b77e69d3798bb402fb82e7d0bdb06c79eeb" %}

package:
  name: fmt
  version: {{ version }}

source:
  fn: fmt-{{ version }}.zip
  url: https://github.com/fmtlib/fmt/releases/download/{{ version }}/fmt-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.1
    - ninja

test:
  commands:
    - test -d ${PREFIX}/include/fmt                     # [unix]
    - test -f ${PREFIX}/lib/libfmt.so                   # [linux]
    - conda inspect linkages -p $PREFIX fmt             # [unix]

about:
  home: http://fmtlib.net
  doc_url: http://fmtlib.net/{{ version }}/
  dev_url: https://github.com/fmtlib/fmt
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Small, safe and fast formatting library
  description: |
    fmt is an open-source formatting library for C++.
    It can be used as a safe alternative to printf
    or as a fast alternative to IOStreams.

extra:
  recipe-maintainers:
    - Sarcasm
