{% set version = "4.0.0" %}
{% set sha256 = "10a9f184d4d66f135093a08396d3b0a0ebe8d97b79f8b3ddb8559f75fe4fcbc3" %}

package:
  name: fmt
  version: {{ version }}

source:
  fn: fmt-{{ version }}.zip
  url: https://github.com/fmtlib/fmt/releases/download/4.0.0/fmt-{{ version }}.zip
  sha256: {{ sha256 }}
  # fix an issue with `make test` during build
  patches:
    - 0001-Fix-a-segfault-in-test-on-glibc-2.26-551.patch
    - 0002-Fix-a-segfault-in-test-on-glibc-2.26-551-take-2.patch

build:
  number: 0

test:
  commands:
    - test -f ${PREFIX}/lib/libfmt.a                    # [unix]
    - test -d ${PREFIX}/include/fmt                     # [unix]

about:
  home: http://fmtlib.net
  doc_url: http://fmtlib.net/{{ version }}/
  dev_url: https://github.com/fmtlib/fmt
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Small, safe and fast formatting library
  description: |
    fmt is an open-source formatting library for C++.
    It can be used as a safe alternative to printf
    or as a fast alternative to IOStreams.

extra:
  recipe-maintainers:
    - Sarcasm
